# https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/storageclass.html
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fast
provisioner: kubernetes.io/vsphere-volume
parameters:
  datastore: VSANDatastore
  diskformat: thin
  fstype: ext3